# Generated by Django 4.1.2 on 2022-10-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
