# Generated by Django 4.1.2 on 2022-10-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('votes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Help', 'Help'), ('Discussion', 'Discussion'), ('Announcement', 'Announcement'), ('Rant', 'Rant'), ('Casual', 'Casual'), ('Other', 'Other')], max_length=12)),
                ('tag0', models.CharField(blank=True, choices=[('General', 'General'), ('Academics', 'Academics'), ('Career', 'Career'), ('Health', 'Health')], max_length=100, null=True)),
                ('tag1', models.CharField(blank=True, choices=[('General', 'General'), ('Academics', 'Academics'), ('Career', 'Career'), ('Health', 'Health')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('is_upvote', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('votes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
