# Generated by Django 4.1.2 on 2022-10-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_user_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
