# Generated by Django 4.1.2 on 2022-10-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_pseudo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pseudo_id',
        ),
    ]
